export const USERINFO_LOGIN = 'USERINFO_LOGIN';
export const USERINFO_LOGOOF = 'USERINFO_LOGOOF';
export const USERINFO_MATCH = 'USERINFO_MATCH';
export const USERINFO_ADDTEAMINFO = 'USERINFO_ADDTEAMINFO';
